# The URL the site will be built for
base_url = "https://jwt-hack.hahwul.com"
title = "JWT-HACK"
theme = "goyo"
description = "A high-performance toolkit for testing, analyzing and attacking JSON Web Tokens"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
bottom_footnotes = true
highlight_theme = "ayu-mirage"

[extra]
logo_text = "JWT-HACK"
logo_image_path = "images/logo.png"
default_thumbnail = "images/preview.jpg"
footer_html = "Powered by <a href='https://www.getzola.org'>Zola</a> and <a href='https://github.com/hahwul/goyo'>Goyo</a>"
twitter_site = "@hahwul"
twitter_creator = "@hahwul"
default_colorset = "dark"
sidebar_expand_depth = 1
disable_root_sidebar_hide = false

nav = [
    { name = "Get Started", url = "/get_started/installation", type = "url", icon = "fa-solid fa-play" },
    { name = "Usage", url = "/usage/decode", type = "url", icon = "fa-solid fa-terminal" },
    { name = "Advanced", url = "/advanced/configuration", type = "url", icon = "fa-solid fa-cogs" },
    { name = "Links", type = "dropdown", icon = "fa-solid fa-link", members = [
        { name = "GitHub", url = "https://github.com/hahwul/jwt-hack", type = "url", icon = "fa-brands fa-github" },
        { name = "Crates.io", url = "https://crates.io/crates/jwt-hack", type = "url", icon = "fa-brands fa-rust" },
        { name = "Creator Blog", url = "https://www.hahwul.com", type = "url", icon = "fa-solid fa-fire-flame-curved" },
        { name = "Contributing", url = "/contributing", type = "url", icon = "fa-solid fa-heart" },
    ] },
]