---
name: jwt-hack
summary: JSON Web Token Hack Toolkit.
description: A high-performance toolkit for testing, analyzing and attacking JSON Web Tokens.
base: core22
grade: stable
confinement: strict
license: MIT
version: v2.0.0
architectures: [amd64, arm64, armhf, i386]

apps:
  jwt-hack:
    command: jwt-hack
    plugs: [home, network, network-bind]
parts:
  jwt-hack:
    source: .
    plugin: rust
    build-packages: []
    override-build: |
      cargo build --release
      cp ./target/release/jwt-hack $SNAPCRAFT_PART_INSTALL/
      snapcraftctl build
