---
name: jwt-hack
summary: JSON Web Token Hack Toolkit.
description: A high-performance toolkit for testing, analyzing and attacking JSON Web Tokens.
base: core20
grade: stable
confinement: strict
license: MIT
version: v2.0.0

apps:
  jwt-hack:
    command: jwt-hack
    plugs: [home, network, network-bind]

parts:
  jwt-hack:
    source: .
    plugin: rust
